# Prompt Tuning 微调配置模板
model_name_or_path: "your-hf-model-name"
output_dir: "output/prompt_tuning"
dataset_path: "data/train.jsonl"
per_device_train_batch_size: 4
epochs: 3
learning_rate: 1e-3
max_seq_length: 512
num_virtual_tokens: 20
fp16: true 